name: EC Service CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: alpine-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - uses: actions/checkout@v2
    - name: Install nodejs
      run: |
        apk update 
        apk add npm
    - run: |
        npm install
        node ./app.js
