name: EC Service CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '15'
    - name: run the application
      env:
        TEST_REPO_ENV: ${{secrets.TEST_REPO_ENV}}
        TEST_ENV: ${{secrets.TEST_ENV}}
      run: |
        echo 'TEST_REPO_ENV: $TEST_REPO_ENV'
        echo 'TEST_ENV: $TEST_ENV'
        npm install
        node ./app.js
